// Strategy properties
//@version=5
// strategy("My First MACD/RSI Algo v3", overlay=true, initial_capital=1000, default_qty_type=strategy.percent_of_equity, default_qty_value=100)
strategy("My First MACD/RSI Algo v3", overlay=true, initial_capital=1000, default_qty_type=strategy.percent_of_equity, default_qty_value=100, commission_type=strategy.commission.percent, commission_value=0.01)

// 1. INDICATORS

// RSI
rsiLength = input(14, title="RSI Length")
rsiValue = ta.rsi(close, rsiLength)

// MACD 
[macdLine, signalLine, histLine] = ta.macd(close, 12, 26, 9)

// Changed from 200 SMA to 50 SMA for intraday momentum
sma50 = ta.sma(close, 50)


// // ENTRY
// // Loosened RSI requirement from 40 to 50
// rsiOversold = rsiValue < 50
// macdBullishCross = ta.crossover(macdLine, signalLine)
// uptrend = close > sma50
// longCondition = rsiOversold and macdBullishCross and uptrend

// // ENTRY
// Turning off RSI and SMA for this test to force trades
// rsiOversold = rsiValue < 50
// uptrend = close > sma50

// CHECK FOR MACD CROSS
macdBullishCross = ta.crossover(macdLine, signalLine)
longCondition = macdBullishCross

// EXECTUE THE ENTRY
if (longCondition)
    strategy.entry("Buy Call", strategy.long)


// EXIT
takeProfitPerc = 0.10 / 100 
stopLossPerc = 0.30 / 100   
takeProfitLevel = strategy.position_avg_price * (1 + takeProfitPerc)
stopLossLevel = strategy.position_avg_price * (1 - stopLossPerc)

if (strategy.position_size > 0)
    strategy.exit("Exit Call", "Buy Call", limit=takeProfitLevel, stop=stopLossLevel)


// INDICATORS
plotshape(series=longCondition, title="Buy Signal", location=location.belowbar, color=color.green, style=shape.triangleup, size=size.small)
plot(sma50, color=color.orange, title="50 SMA", linewidth=2)